groups:
  - name: error_fire
    rules:
      - alert: HighPercentageError
        expr: |
          rate({level="error",serverEnv="prod"} |= "error" [1m])
            > 0
        for: 10m
        labels:
            severity: critical
        annotations:
            summary: High Percentage Error {{ $labels.job }} {{.message}}
