apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true

  - name: Alertmanager
    type: alertmanager
    url: http://alertmanager:9093
    access: proxy
#    orgId: 2
    folder: ''
    jsonData:
      implementation: 'prometheus' # alternatively 'cortex'
    basicAuth: false
    isDefault: false
    editable: true
    # optionally
#    basicAuth: true
#    basicAuthUser: my_user
#    basicAuthPassword: test_password

  - name: Loki
    type: loki
    access: proxy
    folder: ''
#    orgId: 2
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    editable: true
